#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/.shell_common

# twilio autocomplete setup
TWILIO_AC_ZSH_SETUP_PATH=/Users/joshua/.twilio-cli/autocomplete/zsh_setup && test -f $TWILIO_AC_ZSH_SETUP_PATH && source $TWILIO_AC_ZSH_SETUP_PATH;
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/joshua/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/joshua/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/joshua/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/joshua/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

export PATH="$HOME/.bin:$PATH"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source /Users/joshua/.config/broot/launcher/bash/br

# bindkey -v
# bindkey '^R' history-incremental-search-backward

