#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/.shell_common

# OnePassword CLI autocomplete
eval "$(op completion zsh)"; compdef _op op

# twilio autocomplete setup
TWILIO_AC_ZSH_SETUP_PATH=/Users/joshua/.twilio-cli/autocomplete/zsh_setup && test -f $TWILIO_AC_ZSH_SETUP_PATH && source $TWILIO_AC_ZSH_SETUP_PATH;
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/joshua/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/joshua/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/joshua/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/joshua/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

export N_PREFIX=$HOME/.n
export PATH=$N_PREFIX/bin:$PATH
export PATH="$HOME/.bin:$PATH"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

bindkey -v # Vim Keybindings, put before fzf cause otherwise backwards history search keybinding gets messed up
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source /Users/joshua/.config/broot/launcher/bash/br

autoload -U promptinit
promptinit

# Make pure a single-line prompt
# https://github.com/sindresorhus/pure/wiki/Customizations,-hacks-and-tweaks#single-line-prompt
prompt pure
prompt_newline='%666v'
PROMPT=" $PROMPT"

# Show exit code of last command as a separate prompt character
PROMPT='%(?.%F{magenta}.%F{red}❯%F{magenta})❯%f '

# Show number of jobs in prompt
PROMPT='%(1j.[%j] .)%(?.%F{magenta}.%F{red})${PURE_PROMPT_SYMBOL:-❯}%f '


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# virtualenvwrapper settings
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
source /Users/joshua/Library/Python/3.9/bin//virtualenvwrapper.sh

function virtualenv_info {
    [ $VIRTUAL_ENV ] && echo '('`basename $VIRTUAL_ENV`') '
}
PROMPT+='%{$fg[green]%}$(virtualenv_info)%{$reset_color%}%'

